CREATE TABLE usr (
  USER_ID NUMBER(11) NOT NULL PRIMARY KEY,
  FIRST_NAME varchar2(20) DEFAULT NULL,
  LAST_NAME varchar2(20) DEFAULT NULL,
  JOINING_DATE TIMESTAMP DEFAULT NULL,
 ADDRESS_LINE_1 varchar2(50) DEFAULT NULL,
  ADDRESS_LINE_2 varchar2(50) DEFAULT NULL,
  ADDRESS_LINE_3 varchar2(50) DEFAULT NULL,
  CITY varchar2(20) DEFAULT NULL,
  STATE varchar2(20) DEFAULT NULL,
  COUNTRY varchar2(20) DEFAULT NULL
  );
  
CREATE TABLE student (
  STUDENT_USR_ID number(11) NOT NULL,
  ROLL_NO number(11) DEFAULT NULL,
  CONSTRAINT FK_STUDENT_USR_ID FOREIGN KEY (STUDENT_USR_ID) REFERENCES USR (USER_ID)
);

CREATE TABLE employee (
  EMP_USER_ID NUMBER(11) NOT NULL PRIMARY KEY,
  EMP_CODE NUMBER(11) DEFAULT NULL,
  CONSTRAINT FK_EMP_USER_ID FOREIGN KEY (EMP_USER_ID) REFERENCES usr (USER_ID)
);

CREATE TABLE librarian (
  LIBRARIAN_USER_ID number(11) NOT NULL,
  FAV_BOOK varchar(20) NOT NULL,
  CONSTRAINT librarian_ibfk_1 FOREIGN KEY (LIBRARIAN_USER_ID) REFERENCES employee (EMP_USER_ID)
);

CREATE TABLE teacher (
  TEACHER_USR_ID NUMBER(11) NOT NULL,
  DEPARTMENT varchar(20) DEFAULT NULL,
  CONSTRAINT teacher_ibfk_1 FOREIGN KEY (TEACHER_USR_ID) REFERENCES employee (EMP_USER_ID)
); 

CREATE TABLE shelf (
  SHELF_ID NUMBER(11) NOT NULL PRIMARY KEY,
  LOCATION varchar(20) DEFAULT NULL
); 

CREATE TABLE rack (
  RACK_ID NUMBER(11) NOT NULL  PRIMARY KEY,
  RACK_NUMBER NUMBER(11) DEFAULT NULL,
  RACK_SHELF_ID NUMBER(11) DEFAULT NULL,
  CONSTRAINT FK_RACK_SHELF_ID FOREIGN KEY (RACK_SHELF_ID) REFERENCES shelf (SHELF_ID)
);

CREATE TABLE library_resource (
  RESOURCE_ID NUMBER(11) NOT NULL  PRIMARY KEY,
  RESOURCE_NAME varchar(20) DEFAULT NULL,
  AUTHOR varchar(20) DEFAULT NULL,
  PUBLICATION varchar(20) DEFAULT NULL,
  RESOURCE_YEAR NUMBER(11) DEFAULT NULL,
  RESOURCE_TYPE varchar(20) DEFAULT NULL
); 

CREATE TABLE resource_rack (
  RR_RESOURCE_ID NUMBER(11) DEFAULT NULL,
  RR_RACK_ID NUMBER(11) DEFAULT NULL,
  CONSTRAINT FK_RR_RESOURCE_ID FOREIGN KEY (RR_RESOURCE_ID) REFERENCES library_resource (RESOURCE_ID),
  CONSTRAINT FK_RR_RACK_ID FOREIGN KEY (RR_RACK_ID) REFERENCES rack (RACK_ID)
) ;

CREATE TABLE resource_user (
  RU_RESOURCE_ID NUMBER(11) NOT NULL,
  RU_USER_ID NUMBER(11) NOT NULL,
  CONSTRAINT FK_RU_RESOURCE_ID FOREIGN KEY (RU_RESOURCE_ID) REFERENCES library_resource (RESOURCE_ID),
  CONSTRAINT FK_RU_USER_ID FOREIGN KEY (RU_USER_ID) REFERENCES usr (USER_ID)
) ;

CREATE SEQUENCE  "USR_SEQUENCE"  MINVALUE 1 MAXVALUE 99999999999 INCREMENT BY 1 START WITH 10000000001 CACHE 20 NOORDER  NOCYCLE ;
CREATE SEQUENCE  "RESOURCE_SEQUENCE"  MINVALUE 1 MAXVALUE 99999999999 INCREMENT BY 1 START WITH 5001 CACHE 20 NOORDER  NOCYCLE ;
CREATE SEQUENCE  "RACK_SEQUENCE"  MINVALUE 1 MAXVALUE 99999999999 INCREMENT BY 1 START WITH 101 CACHE 20 NOORDER  NOCYCLE ;
CREATE SEQUENCE  "SHELF_SEQUENCE"  MINVALUE 1 MAXVALUE 99999999999 INCREMENT BY 1 START WITH 501 CACHE 20 NOORDER  NOCYCLE ;
